### ISSUE TITLE
change license to less strict?

### ISSUE THREAD

**Issue by ryaneberly** [tn5250j/tn5250j#1]
I know this came up years ago in the mailing list, but any chance of changing the GPL license to one that plays nicer with other open source licenses.

EPL, BSD or MIT for example.

Something that plays better with Eclipse and even JUnit would be nice.

**Comment by nitram509** [comment]
Good point.
Changing the license means, to my naive understanding, to contact every author and ask for permission - this is a challenging task in itself.

If you know another legal way to change the license, I'm open for any recommendations.

**Comment by ryaneberly** [comment]
I think you summed it up correctly -- any idea how many contributors there have been?

**Comment by nitram509** [comment]
See https://github.com/tn5250j/migration/issues/1

Feel free to contact them to get the approval.

**Comment by kjpou1** [comment]
Why does the GPL not play well with Eclipse or JUnit?

**Comment by ryaneberly** [comment]
Good question, i'm not an expert on the licensing stuff, but see here
https://eclipse.org/legal/eplfaq.php#GPLCOMPATIBLE

**Comment by ryaneberly** [comment]
so far heard back from 4/13.  thanks to all.

"I'm fine with changing the license fro GPL to BSD" - Stephen Kennedy 
"I have no problem with whatever license" - Maurizio Brilli 
"I agree to switch to BSD." - Martin W. Kirst
"I have no objections." - Joep Beckeringh

**Comment by bvansomeren** [comment]
Hi, I'm 
golthar             =   Barry van Someren <golthar@users.sourceforge.net> and got an email about this a while ago. (It went to an inbox I didn't check often enough ,sorry)

Personally I don't mind the change at all, unfortunately the work was done as part of my employment way back and I'm unsure where to go to get the proper permissions as I haven't worked there for more than 10 years.

If there is not a lot of code involved it might make sense to scrap / rewrite them. 
I'm surprised any of that code still exists in the codebase!

**Comment by ryaneberly** [comment]
Thanks Barry.
    I've heard back from about half of the contributors, I don't think it's
going to happen :-).  It was worth a try.

On Tue, Aug 23, 2016 at 3:39 AM, Barry van Someren <notifications@github.com

**Comment by cycloon** [comment]
Should we close this issue then?

**Comment by ryaneberly** [comment]
sounds good.
