### ISSUE TITLE
STRPCCMD incorrect truncated at 122

### ISSUE THREAD

**Issue by zenovalle** [tn5250j/tn5250j#4]
Hello everyone,
before v7.2 the length limit for the PCCMD parameter was 123 characters, but when the command is launched the emulator seems to truncate it at 122.

**Comment by zenovalle** [comment]
Done a pull request: https://github.com/tn5250j/tn5250j/pull/7

**Comment by nitram509** [comment]
Splitted this issue in Bug and Enhancement #13

**Comment by zenovalle** [comment]
It's fixed now.
