### ISSUE TITLE
SYSATTN

### ISSUE THREAD

**Issue by fneurieser** [tn5250j/tn5250j#5]
Hello,
thanks for that great tool. Just one question: how can I get the sysattn command on a key?
I can't find any hint on this.

regards
franz-georg

**Comment by duncan3dc** [comment]
Is that the same as `System Request`? If so this can be mapped using the "Map keys..." option on the context menu:
![system-request](https://cloud.githubusercontent.com/assets/546811/15702458/00ef8f7a-27d8-11e6-9671-a23c7521ee33.png)

**Comment by fneurieser** [comment]
Okay that was it, thanks a lot
