### ISSUE TITLE
TN5250jLogFactory customLogger probably not implemented correctly

### ISSUE THREAD

**Issue by SaschaS93** [tn5250j/tn5250j#52]
In TN5250jLogFactory there is a customLogger that can be set externally via a system property. But that doesn't work at the moment.

The customLogger is loaded with the following line in the static block:
`String  customLogger = System.getProperty(TN5250jLogFactory.class.getName());`

And it's used in the method TN5250jLogFactory.getLogger.

But the getLogger method uses the static attribute customLogger and in the static block the String customLogger is just defined locally. I think it should be set on the static attribute and not locally. Currently, using it in getLogger makes no sense, as it is always null. So currently no customLogger can be used.

The problem is easy to solve by changing the line 
`String  customLogger = System.getProperty(TN5250jLogFactory.class.getName());`
to 
`customLogger = System.getProperty(TN5250jLogFactory.class.getName());`

Then the static attribute is set and the customLogger can be set via the system properties.

**Comment by SaschaS93** [comment]
I corrected it, wrote a test and did a pull request. See #53

**Comment by szsascha** [comment]
Thanks for merging
