### ISSUE TITLE
Any kind of installation instructions would be very appreciated.

### ISSUE THREAD

**Issue by HerbertPfeifer** [tn5250j/tn5250j#60]
For an IBMi specialist with not too much java experience it is very hard to receive a zip with lots of files and lots of text - but no instruction or idea whatsoever on how to get this thing running. Or is it there but only hard to find? Please could you add an old fashioned install.txt or something?

**Comment by rsov** [comment]
There is some documentation hosted here: http://tn5250j.org/docs/installation/

**Comment by HerbertPfeifer** [comment]
Thanks, that was easy.
