### ISSUE TITLE
How to transfer the settings (screen colors, keyboard etc) to an other machine?

### ISSUE THREAD

**Issue by mm735** [tn5250j/tn5250j#64]
I use and appreciate  tn5250j on a mac mini. If I'm out I use a mac book and I don't want to do all of the configurations again.

**Comment by nitram509** [comment]
tn5250j stores all settings in various files in your home folder in a path called ".tn5250j".
you can enter it in Finder, when you press CMD+SHIFT+G and then enter ~/.tn5250j

simply copy all these files to your Mac Book and you're ready to go.
