### ISSUE TITLE
Use without screen. Scraping

### ISSUE THREAD

**Issue by dvidalg** [tn5250j/tn5250j#69]
Hi, I want to connect to an AS400 but without a screen.
I need to automate some tasks and I need to do it in a java program writed by me without any screen, gui or person.

I have tested with the ExampleEmbeddedMinimalBootstrap and it connect correctly and shows the main AS400 screen.
But when I use my program and try to read the characters all characters are 0x00

Anyone could help me?
Here is my code:

    public static void main(String[] args){
        try {
            String system = "192.168.168.35"; // TODO: your IP/hostname
            System.setProperty("emulator.settingsDirectory", File.createTempFile("tn5250j", "settings").getAbsolutePath());
            ConfigureFactory.getInstance();
            org.tn5250j.tools.LangTool.init();
            SessionConfig config = new SessionConfig(system, system);
            config.setProperty("font", "Lucida Sans Typewriter Regular"); // example config
            Session5250 session	= new Session5250(new Properties(), system, system, config);
            SessionBean sessionBean = new SessionBean(session);
            sessionBean.setHostName(system);
            sessionBean.setCodePage("Cp273");
            sessionBean.setNoSaveConfigFile();
            sessionBean.setScreenSize("27x132");
            sessionBean.setDeviceName("devname");

            session = sessionBean.getSession();
            Screen5250 screen = session.getScreen();
            char [] buffer = new char[1920];
            StringBuilder sb = new StringBuilder();
            Thread.sleep(3000L);
            screen.GetScreen(buffer, 1920, TN5250jConstants.PLANE_TEXT);
            String showme = new String(buffer);
            for(int i=0;i<showme.length();i+=80) {
                sb.append(showme.substring(i, i+80));
                sb.append("\n");
            }
            System.out.println(sb.toString());
            session.disconnect();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

Thanks :)

**Comment by SaschaS93** [comment]
Hi dvidalg,

I think you simply forgot to connect the session. After I added "session.connect()" it worked for me. See the example below.

```
	public static void main(String[] args){
	    try {
	        String system = "pub400.com"; // TODO: your IP/hostname
	        System.setProperty("emulator.settingsDirectory", File.createTempFile("tn5250j", "settings").getAbsolutePath());
	        ConfigureFactory.getInstance();
	        org.tn5250j.tools.LangTool.init();
	        SessionConfig config = new SessionConfig(system, system);
	        config.setProperty("font", "Lucida Sans Typewriter Regular"); // example config
	        Session5250 session	= new Session5250(new Properties(), system, system, config);
	        SessionBean sessionBean = new SessionBean(session);
	        sessionBean.setHostName(system);
	        sessionBean.setCodePage("Cp273");
	        sessionBean.setNoSaveConfigFile();
	        sessionBean.setScreenSize("27x132");
	        sessionBean.setDeviceName("devname");

	        session = sessionBean.getSession();
	        session.connect();
	        Screen5250 screen = session.getScreen();
	        char [] buffer = new char[1920];
	        StringBuilder sb = new StringBuilder();
	        Thread.sleep(3000L);
	        screen.GetScreen(buffer, 1920, TN5250jConstants.PLANE_TEXT);
	        String showme = new String(buffer);
	        for(int i=0;i<showme.length();i+=80) {
	            sb.append(showme.substring(i, i+80));
	            sb.append("\n");
	        }
	        System.out.println(sb.toString());
	        session.disconnect();
	    } catch (Exception e) {
	        e.printStackTrace();
	    }
	}
```

I would recommend to have a look at the following. This projects uses also some 5250 scraping techniques on plain Java Sockets but without the tn5250 overhead. It's made for monitoring with nagios / icinga.

https://github.com/cjt74392/check_as400

I hope this will help you. :)

**Comment by dvidalg** [comment]
It works!, thanks :)
