### ISSUE TITLE
0.8.0-Beta 1, cannot open settings

### ISSUE THREAD

**Issue by OldNESJunkie** [tn5250j/tn5250j#71]
As the topic states, you cannot open the settings for fonts, etc.  Right click within the application and clicking on settings results in the application freezing up and you have to end the task.  Works fine in 0.7.6.  Tried a fresh install of 0.8.0-Beta 1, also just copying over the tn5250j.jar file of a working 0.7.6, same issue.

Windows 10 x64
JRE8u281
32GB RAM
AMD Ryzen 9 4900H
AMD RX5600M
1TB Samsung SSD

**Comment by nitram509** [comment]
Hi @OldNESJunkie,

thanks for reporting this issue.
Unfortunately, I can't reproduce that issue on my machine.
Is there a chance you could send the log file, so I could check, what's going on?

Typically, you will find the log file in your user's home directory in path .tn5250j.

**Comment by OldNESJunkie** [comment]
Well, I don't see any log files, but I just copied the tn5250j-0.8.0-Snapshot-no-depedencies.jar into my working 0.7.6 and was able to open the settings without issue this time.  Just updated to JRE8u291 yesterday, maybe that had something to do with fixing it, don't know.  I'll let you know and send the log file if I can reproduce it again.  Love it when things break/fix themselves.

**Comment by nitram509** [comment]
Thank you very much for that feedback.

Indeed - with this new Version, a Java 1.8 Runtime is required.
